###########################################################################
###                  Application Settings - LOCAL
###########################################################################
#spring:
#  config:
#    activate:
#      on-profile: local
#  # 데이터베이스 연결 및 설정
#  datasource:
##    driver-class-name: com.mysql.cj.jdbc.Driver
##    url: jdbc:mysql://localhost:3306/testdb?autoReconnect=true&autoReconnection=true&autoReconnectForPools=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
##    username: root
##    password:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./db/testdb;AUTO_SERVER=TRUE
##    url: jdbc:h2:tcp://localhost/~/testdb
#    username: sa
#    password:
#    tomcat:
#      test-while-idle: true
#      validation-query: SELECT 1
#  # H2 DB
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  # 메일 설정
#  mail:
#    username: username@naver.com
#    password: password123
#    host: smtp.naver.com
#    port: 587
#  # JPA 설정
#  jpa:
#    properties:
#      hibernate:
##        format_sql: true
##        highlight_sql: true
##        use_sql_comments: true
#        hbm2ddl:
#          auto: update
#
## 로그 설정
#logging:
##  file:
##    name: logs/default.log
#  #  pattern:
#  #    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] %logger[%method:%line] - %msg%n"
#  #    file: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] %logger[%method:%line] - %msg%n"
#  #    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
#  logback:
#    rollingpolicy:
#      file-name-pattern: "logs/default.%d{yyyy-MM-dd}.%i"
#      max-history: 3
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    #    org.hibernate.type.descriptor.sql: trace
#    com.example: debug
#
##P6spy
#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true
#
###########################################################################
###                  AWS S3 Settings
###########################################################################
#cloud:
#  aws:
#    credentials:
#      profile: #fakedata_dev
#      # S3 접근 USER 설정
#      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
#      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRETKEY}
#    region:
#      # S3 설정 확인
#      static: ap-northeast-2
#    s3:
#      bucket: #demo-dev-bucket
#      url: #https://{puuid}.cloudfront.net
#      role:
#        arn: #arn:aws:iam::428646110308:role/demo-dev-upload-s3-limited-role
#        session:
#          name: #demo-dev-upload-s3-limited-role
#    stack:
#      auto: false
#
#
###########################################################################
###                  Upload Configurations
###########################################################################
#upload:
#  base-path: upload/
#  editor-path: editor/
#  board-path: board/
#
#
###########################################################################
###                  Site Configurations
###########################################################################
#
#
#
