##########################################################################
##                  Application Settings (upload)
##########################################################################
upload:
  base-path: upload/
  editor-path: editor/
  board-path: board/