##########################################################################
##                  Application Settings - develop (cloud)
##########################################################################
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false