##########################################################################
##                  Application Settings - local (cloud)
##########################################################################
demo:
  pc-url: fakadata
  mo-url: fakadata