##########################################################################
##                  Application Settings - local (oauth2)
##########################################################################
