##########################################################################
##                  Application Settings - develop (cloud)
##########################################################################
demo:
  pc-url: fakadata
  mo-url: fakadata