##########################################################################
##                  Application Settings - develop (oauth2)
##########################################################################
