##########################################################################
##                  Application Settings - local (oauth2)

#  로그인 요청
#  http://{domain}/oauth2/authorization/{registrationId}
#  Spring Security에서 기본적으로 제공하는 URL이 있다.
#  시큐리티에서 이미 구현을 해두었고, 따로 Controller를 만들지 않아도 된다.

#  리다이렉트 URL
#  http://{domain}/login/oauth2/code/{registrationId}
#  Spring Security에서 기본적으로 제공하는 URL이 있다.
#  시큐리티에서 이미 구현을 해두었고, 따로 Controller를 만들지 않아도 된다.

##########################################################################

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: "http://localhost:8080/api/v1/account/oauth2/callback/google"
            authorization-grant-type: authorization_code
            # google API의 범위 값
            scope:
              - profile
              - email

          kakao:
            client-id:
            client-secret:
            redirect-uri: "http://localhost:8080/api/v1/account/oauth2/callback/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            # kakao 개인 정보 동의 항목 설정의 ID 값
            scope:
#              - openid
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao

          naver:
            client-id:
            client-secret:
            redirect-uri: "http://localhost:8080/api/v1/account/oauth2/callback/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: naver

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
