##########################################################################
##                  Application Settings - local (base)
##########################################################################
spring:
#  config:
#    activate:
#      on-profile: local

  # 메일 설정
  mail:
    username: username@naver.com
    password: password123
    host: smtp.naver.com
    port: 587

  # JPA 설정
  jpa:
    properties:
      hibernate:
        #        format_sql: true
        #        highlight_sql: true
        #        use_sql_comments: true
        hbm2ddl:
          auto: update

