##########################################################################
##                  Application Settings - develop (log)
##########################################################################
# 로그 설정
logging:
  #  file:
  #    name: logs/default.log
  #  pattern:
  #    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] %logger[%method:%line] - %msg%n"
  #    file: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] %logger[%method:%line] - %msg%n"
  #    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "logs/default.%d{yyyy-MM-dd}.%i"
      max-history: 3
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    #    org.hibernate.type.descriptor.sql: trace
    com.example: debug

#P6spy
decorator:
  datasource:
    p6spy:
      enable-logging: true